import React, { useState, useEffect } from "react";
import api from "../utils/api";
import NewsCard from "./NewsCard";
import "./AiFeatures.css";

const STOCK_OPTIONS = [
  "ALL",
  "RELIANCE",
  "TCS",
  "INFY",
  "HDFCBANK",
  "SBIN",
  "BHARTIARTL",
  "WIPRO",
  "ITC",
  "M&M",
  "TATAPOWER",
  "HINDUNILVR",
  "KPITTECH",
  "ONGC",
  "EVEREADY",
  "JUBLFOOD",
  "QUICKHEAL",
  "NIFTY",
];

const AiNews = () => {
  const [articles, setArticles] = useState([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [selectedStock, setSelectedStock] = useState("ALL");
  const [sentimentFilter, setSentimentFilter] = useState("ALL");
  const [searchTerm, setSearchTerm] = useState("");
  const [error, setError] = useState(null);

  const fetchNews = async (stock = selectedStock) => {
    setLoading(true);
    setError(null);
    try {
      const params = { limit: 40 };
      if (stock && stock !== "ALL") {
        params.symbol = stock;
      }
      const res = await api.get("/api/news", { params });
      setArticles(res.data?.articles || []);
    } catch (err) {
      console.error("Failed to fetch news:", err);
      setError("Unable to load financial news right now. Please try again later.");
    } finally {
      setLoading(false);
    }
  };

  const handleRefreshFeeds = async () => {
    setRefreshing(true);
    try {
      await api.post("/api/news/fetch");
      await fetchNews(selectedStock);
    } catch (err) {
      console.error("Refresh feeds error:", err);
    } finally {
      setRefreshing(false);
    }
  };

  useEffect(() => {
    fetchNews(selectedStock);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedStock]);

  const handleStockChange = (e) => {
    setSelectedStock(e.target.value);
  };

  const handleAnalysisUpdated = (articleId, newAnalysis) => {
    setArticles((prev) =>
      prev.map((art) => (art._id === articleId ? { ...art, analysis: newAnalysis } : art))
    );
  };

  // Filter articles based on sentiment and search query
  const filteredArticles = articles.filter((art) => {
    // Sentiment filter
    if (sentimentFilter !== "ALL") {
      if (!art.analysis || art.analysis.direction?.toUpperCase() !== sentimentFilter) {
        return false;
      }
    }
    // Search filter
    if (searchTerm.trim() !== "") {
      const q = searchTerm.toLowerCase();
      const inTitle = (art.title || "").toLowerCase().includes(q);
      const inDesc = (art.description || "").toLowerCase().includes(q);
      const inSymbol = (art.symbol || "").toLowerCase().includes(q);
      return inTitle || inDesc || inSymbol;
    }
    return true;
  });

  return (
    <div style={{ padding: "24px 30px" }}>
      {/* Header */}
      <div className="ai-header-container">
        <div>
          <h3 className="ai-page-title">
            <span> AI Financial News Intelligence</span>
          </h3>
          <p className="ai-page-subtitle">
            Real-time financial RSS aggregation analyzed with structured LLM market insights.
          </p>
        </div>

        <button
          className="ai-btn-secondary"
          onClick={handleRefreshFeeds}
          disabled={refreshing}
        >
          {refreshing ? " Updating Feeds..." : " Refresh RSS Feeds"}
        </button>
      </div>

      {/* AI Safety Disclaimer */}
      <div className="ai-disclaimer-banner">
        <span></span>
        <div>
          <strong>AI Market Insight Notice:</strong> Analysis is generated by AI based on available financial news feeds. It reflects probabilistic sentiment and does not constitute guaranteed financial or investment advice.
        </div>
      </div>

      {/* Filter & Search Bar */}
      <div className="ai-filter-bar">
        <input
          type="text"
          className="ai-search-input"
          placeholder="Search news by headline, keyword, or company..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
        />

        <div style={{ display: "flex", alignItems: "center", gap: "6px" }}>
          <span style={{ fontSize: "0.82rem", color: "#64748b", fontWeight: 600 }}>Stock:</span>
          <select className="ai-select" value={selectedStock} onChange={handleStockChange}>
            {STOCK_OPTIONS.map((stock) => (
              <option key={stock} value={stock}>
                {stock === "ALL" ? "All Instruments" : stock}
              </option>
            ))}
          </select>
        </div>
      </div>

      {/* Sentiment Filter Pills */}
      <div className="filter-pills-row">
        <button
          className={`filter-pill ${sentimentFilter === "ALL" ? "active" : ""}`}
          onClick={() => setSentimentFilter("ALL")}
        >
          All Sentiments
        </button>
        <button
          className={`filter-pill ${sentimentFilter === "BULLISH" ? "active" : ""}`}
          onClick={() => setSentimentFilter("BULLISH")}
        >
           Bullish
        </button>
        <button
          className={`filter-pill ${sentimentFilter === "BEARISH" ? "active" : ""}`}
          onClick={() => setSentimentFilter("BEARISH")}
        >
           Bearish
        </button>
        <button
          className={`filter-pill ${sentimentFilter === "NEUTRAL" ? "active" : ""}`}
          onClick={() => setSentimentFilter("NEUTRAL")}
        >
           Neutral
        </button>
      </div>

      {/* Content Area */}
      {loading ? (
        <div className="state-container">
          <div className="state-icon"></div>
          <div className="state-title">Loading Financial Intelligence...</div>
          <p className="state-desc">Fetching latest news feeds and AI market insights.</p>
        </div>
      ) : error ? (
        <div className="state-container">
          <div className="state-icon"></div>
          <div className="state-title">Unable to Load News</div>
          <p className="state-desc">{error}</p>
          <button className="ai-btn-primary" onClick={() => fetchNews(selectedStock)}>
            Try Again
          </button>
        </div>
      ) : filteredArticles.length > 0 ? (
        <div className="news-cards-grid">
          {filteredArticles.map((article) => (
            <NewsCard
              key={article._id}
              article={article}
              onAnalysisGenerated={handleAnalysisUpdated}
            />
          ))}
        </div>
      ) : (
        <div className="state-container">
          <div className="state-icon"></div>
          <div className="state-title">No Relevant News Found</div>
          <p className="state-desc">
            {searchTerm || sentimentFilter !== "ALL" || selectedStock !== "ALL"
              ? "No articles matched your active filters. Try broadening your search or resetting filters."
              : "No financial news articles are currently available."}
          </p>
          {(searchTerm || sentimentFilter !== "ALL" || selectedStock !== "ALL") && (
            <button
              className="ai-btn-secondary"
              onClick={() => {
                setSearchTerm("");
                setSentimentFilter("ALL");
                setSelectedStock("ALL");
              }}
            >
              Reset Filters
            </button>
          )}
        </div>
      )}
    </div>
  );
};

export default AiNews;
